name: habit_tracker
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.5
  #build_runner: ^2.4.5
  build_resolvers: ^2.3.0
  async: ^2.11.0
  boolean_selector: ^2.1.1
  characters: ^1.3.0
  collection: ^1.19.0
  json_serializable: ^6.0.1
  material_color_utilities: ^0.11.1
  flutter_slidable: ^3.1.2
  flutter_heatmap_calendar: ^1.0.5
  shared_preferences: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0
  clock: ^1.1.1
  leak_tracker: ^10.0.7
  leak_tracker_flutter_testing: ^3.0.8
  build_runner: ^2.4.5
  flutter_launcher_icons: ^0.14.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

dependency_overrides:
  #_fe_analyzer_shared: ^77.0.0
  analyzer: ^6.0.0
  #dart_style: ^2.3.7
  fake_async: ^1.3.2
  js: ^0.7.1
  matcher: ^0.12.17
  meta: ^1.16.0
  path: ^1.9.1
  source_span: ^1.10.1
  string_scanner: ^1.4.0
  test_api: ^0.7.4
  vm_service: ^15.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
